PROJECT = spinor-firmware

CFILES += src/main.c 
CFILES += src/dronecan.c
CFILES += src/setup.c
CFILES += src/isr.c
CFILES += src/encoder.c
CFILES += src/foc.c
CFILES += src/math.c
CFILES += src/adc.c
CFILES += src/thermistor.c
CFILES += src/ControllerStateMachine.c

CFILES += lib/libcanard/canard.c lib/libcanard/drivers/stm32/canard_stm32.c
SHARED_DIR += lib lib/libcanard 

# DSDL autogenerated encode/decode for dronecan
SHARED_DIR += lib/dsdl/dsdl_generated/include
CFILES += lib/dsdl/dsdl_generated/src/uavcan.protocol.NodeStatus.c
CFILES += lib/dsdl/dsdl_generated/src/uavcan.protocol.debug.KeyValue.c
CFILES += lib/dsdl/dsdl_generated/src/uavcan.protocol.param.GetSet_req.c
CFILES += lib/dsdl/dsdl_generated/src/uavcan.protocol.param.GetSet_res.c

DEVICE = stm32f072cbt6
OOCD_INTERFACE = stlink
OOCD_TARGET = stm32f0x
INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))
OPENCM3_DIR = lib/libopencm3


include $(OPENCM3_DIR)/mk/genlink-config.mk
include rules.mk
include $(OPENCM3_DIR)/mk/genlink-rules.mk
