#pragma once

#include "libopencm3/stm32/gpio.h"
#include "libopencm3/stm32/adc.h"

#define SPI_NCS_PORT GPIOA
#define SPI_NCS_PIN GPIO15
#define SPI_CLK_MISO_MOSI_PORT GPIOB
#define SPI_CLK_MISO_MOSI_PIN GPIO3 | GPIO4 | GPIO5

#define LED_PORT GPIOA
#define LED_R GPIO4
#define LED_B GPIO3

#define IABC_PORT GPIOA
#define IABC_PIN GPIO0 | GPIO1 | GPIO2
#define IA_CHSEL ADC_CHSELR_CHSEL(0)
#define IB_CHSEL ADC_CHSELR_CHSEL(1)
#define IC_CHSEL ADC_CHSELR_CHSEL(2)

#define TEMP_PORT GPIOA
#define TEMP_PIN GPIO6 | GPIO7
#define TMTR_CHSEL ADC_CHSELR_CHSEL(6)
#define TFET_CHSEL ADC_CHSELR_CHSEL(7)

#define VBUS_PORT GPIOB
#define VBUS_PIN GPIO0
#define VBUS_CHSEL ADC_CHSELR_CHSEL(8)

#define ADC_CHSELR_IA_IB_IC (IA_CHSEL | IB_CHSEL | IC_CHSEL)
#define ADC_CHSELR_IA_IB_IC_VBUS (ADC_CHSELR_IA_IB_IC | VBUS_CHSEL)
#define ADC_CHSELR_IA_IB_IC_TMTR (ADC_CHSELR_IA_IB_IC | TMTR_CHSEL)
#define ADC_CHSELR_IA_IB_IC_TFET (ADC_CHSELR_IA_IB_IC | TFET_CHSEL)

#define CAN_PORT GPIOB
#define CAN_PIN GPIO8 | GPIO9

#define PWML_PORT GPIOB
#define PWML_PIN GPIO13 | GPIO14 | GPIO15
#define PWMH_PORT GPIOA
#define PWMH_PIN GPIO8 | GPIO9 | GPIO10
